### ISSUE TITLE
Odoo quickconnect: clicking "sign in" leads to an error (cf. screenshot)

### ISSUE THREAD

**Issue by LoredanaLrpz** [Maurin3/Userscripts#19]
![image](https://github.com/Maurin3/Userscripts/assets/95279628/d96d13b2-b062-4521-b194-76fa7cd59f7e)

**Comment by Maurin3** [comment]
Hello @LoredanaLrpz! Thanks for sharing this issue!
I'll try to fix this asap.

(I'm a bit surprised someone uses this userscript 😃)

**Comment by LoredanaLrpz** [comment]
Thanks @Maurin3 ! (Oh, and I'm surprised no one does haha it's useful)

**Comment by Maurin3** [comment]
Hello @LoredanaLrpz! Can you please check if it's now ok? The link with the fix is here: https://github.com/Maurin3/Userscripts/raw/c7fb7c838b96f613a194e00bc28984bd841f46d8/odoo-quick-connect.user.js. It will ask you to reinstall it, but don't worry, it's normal.

**Comment by Maurin3** [comment]
Hello @LoredanaLrpz ! Did you have time to check if this works with the fix?

**Comment by LoredanaLrpz** [comment]
Hey @Maurin3, sorry for the late reply
I tested it but it still didn't work so I just stopped using it

Thanks for trying to fix this
I hope you have a great day!
